import type { CategoryId } from "./categories";
import type { EmotionType, ActionItem } from "@dreamhub/ai";

export interface Thought {
  id: string;
  title: string;
  body: string;
  summary: string;
  category: CategoryId;
  tags: string[];
  keywords: string[];
  createdAt: string;
  isFavorite: boolean;
  isArchived: boolean;
  isPinned: boolean;
  importance: number;
  emotion: EmotionType;
  emotionSecondary?: EmotionType;
  valence: number;
  emotionConfidence: number;
  actionItems: ActionItem[];
  peopleMentioned: string[];
  placesMentioned: string[];
}

export interface Connection {
  sourceId: string;
  targetId: string;
  score: number;
  reason: string;
}

export const mockThoughts: Thought[] = [
  {
    id: "1",
    title: "Marketing automation idea",
    body: "We could build an AI tool that auto-generates social media content from a single blog post. It would save hours of manual work every week. The key insight is that most social posts are just reformatted versions of longer content — an AI could handle the transformation automatically.",
    summary: "AI-powered social media content generator from blog posts",
    category: "ideas",
    tags: ["marketing", "AI", "automation"],
    keywords: ["content generation", "social media", "productivity"],
    createdAt: "2026-02-12T14:30:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: true,
    importance: 5,
    emotion: "excited",
    emotionSecondary: "determined",
    valence: 0.8,
    emotionConfidence: 0.9,
    actionItems: [
      { text: "Build a prototype of the content generator", completed: false },
      { text: "Research existing social media automation tools", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "2",
    title: "Project deadline discussion",
    body: "Met with the team to discuss Q1 deliverables. We agreed to push the launch to March 15th to ensure quality. Need to update the roadmap and communicate the change to stakeholders. Sarah will handle the client communication.",
    summary: "Q1 launch pushed to March 15th for quality assurance",
    category: "work",
    tags: ["project", "meeting", "deadline"],
    keywords: ["Q1", "launch", "roadmap"],
    createdAt: "2026-02-12T11:15:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "determined",
    emotionSecondary: "calm",
    valence: 0.2,
    emotionConfidence: 0.8,
    actionItems: [
      { text: "Update the roadmap", completed: false },
      { text: "Communicate the change to stakeholders", completed: false },
    ],
    peopleMentioned: ["Sarah"],
    placesMentioned: [],
  },
  {
    id: "3",
    title: "Feeling grateful today",
    body: "Had a really productive morning. Coffee tasted amazing, got through my inbox, and had a great brainstorm session. Small wins matter. I should remember to appreciate these quiet, productive days more often.",
    summary: "Productive morning with small wins boosting gratitude",
    category: "emotions",
    tags: ["gratitude", "productivity", "mindset"],
    keywords: ["morning routine", "appreciation", "small wins"],
    createdAt: "2026-02-12T09:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 2,
    emotion: "grateful",
    valence: 0.7,
    emotionConfidence: 0.95,
    actionItems: [],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "4",
    title: "React Server Components deep dive",
    body: "Spent 2 hours reading about RSC patterns. The mental model shift from client-first to server-first is significant. Need to practice more. Key takeaway: think of the server as the default, and only opt into client when you need interactivity.",
    summary: "Learning RSC patterns and server-first mental model",
    category: "learning",
    tags: ["React", "RSC", "frontend"],
    keywords: ["server components", "Next.js", "architecture"],
    createdAt: "2026-02-11T20:45:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "curious",
    emotionSecondary: "determined",
    valence: 0.5,
    emotionConfidence: 0.85,
    actionItems: [
      { text: "Practice RSC patterns with a sample project", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "5",
    title: "Morning run routine",
    body: "Ran 5km in 28 minutes. Felt strong today. The new shoes make a big difference on pavement. Want to try interval training next week. Heart rate stayed in zone 2 for most of the run.",
    summary: "5km run in 28min, planning interval training next",
    category: "health",
    tags: ["running", "exercise", "routine"],
    keywords: ["5km", "cardio", "training"],
    createdAt: "2026-02-11T07:30:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "determined",
    emotionSecondary: "excited",
    valence: 0.6,
    emotionConfidence: 0.8,
    actionItems: [
      { text: "Try interval training next week", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "6",
    title: "Coffee shop business concept",
    body: "What if there was a coffee shop that doubles as a coworking space with AI-powered networking? Match people based on their interests and goals. The space would have quiet zones, meeting pods, and a community board powered by AI recommendations.",
    summary: "AI-powered coworking coffee shop with smart networking",
    category: "dreams",
    tags: ["business", "coffee-shop", "networking"],
    keywords: ["coworking", "community", "AI matching"],
    createdAt: "2026-02-10T16:20:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: true,
    importance: 5,
    emotion: "hopeful",
    emotionSecondary: "excited",
    valence: 0.85,
    emotionConfidence: 0.88,
    actionItems: [
      { text: "Research coworking space business models", completed: false },
      { text: "Sketch out the floor plan concept", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "7",
    title: "Monthly budget review",
    body: "Reviewed expenses for January. Subscription costs are creeping up — need to audit and cancel unused services. Savings rate at 32%. Goal is to hit 40% by June. Major expenses: rent, food delivery, streaming services.",
    summary: "January expense review: audit subscriptions, 32% savings rate",
    category: "finance",
    tags: ["budget", "savings", "subscriptions"],
    keywords: ["expenses", "financial planning", "audit"],
    createdAt: "2026-02-10T10:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "determined",
    valence: 0.1,
    emotionConfidence: 0.75,
    actionItems: [
      { text: "Audit and cancel unused subscriptions", completed: false },
      { text: "Hit 40% savings rate by June", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "8",
    title: "Catch up with Alex",
    body: "Had lunch with Alex today. He's thinking about switching careers from finance to tech. Offered to connect him with some people in my network. We should meet more regularly — it's been too long.",
    summary: "Lunch with Alex, helping with his career transition to tech",
    category: "relationships",
    tags: ["Alex", "networking", "career"],
    keywords: ["friendship", "career advice", "mentoring"],
    createdAt: "2026-02-09T13:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "grateful",
    emotionSecondary: "calm",
    valence: 0.6,
    emotionConfidence: 0.82,
    actionItems: [
      { text: "Connect Alex with people in my tech network", completed: false },
      { text: "Schedule regular meetups with Alex", completed: false },
    ],
    peopleMentioned: ["Alex"],
    placesMentioned: [],
  },
  {
    id: "9",
    title: "AI chatbot learning memo",
    body: "Explored different chatbot frameworks today. LangChain seems powerful but complex. For our use case, a simpler approach with direct OpenAI API calls might work better. Need to prototype both and compare.",
    summary: "Comparing chatbot frameworks: LangChain vs direct API calls",
    category: "learning",
    tags: ["AI", "chatbot", "LangChain"],
    keywords: ["framework comparison", "OpenAI", "prototyping"],
    createdAt: "2026-02-09T10:30:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "curious",
    valence: 0.4,
    emotionConfidence: 0.9,
    actionItems: [
      { text: "Prototype with LangChain", completed: false },
      { text: "Prototype with direct OpenAI API calls", completed: false },
      { text: "Compare both approaches", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "10",
    title: "Digital marketing trends",
    body: "Short-form video is still dominating. TikTok's algorithm rewards consistency over production quality. Key insight: authentic content outperforms polished ads. Should apply this to our content strategy.",
    summary: "Short-form video dominates; authenticity beats production quality",
    category: "ideas",
    tags: ["marketing", "TikTok", "content-strategy"],
    keywords: ["short-form video", "algorithm", "authenticity"],
    createdAt: "2026-02-08T15:45:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "curious",
    emotionSecondary: "determined",
    valence: 0.3,
    emotionConfidence: 0.78,
    actionItems: [
      { text: "Apply authenticity-first approach to content strategy", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "11",
    title: "Evening meditation reflection",
    body: "Tried a 20-minute body scan meditation tonight. Found it much easier to focus than breath-based meditation. My mind wanders less when there's a physical anchor point. Will stick with this style for the next week.",
    summary: "Body scan meditation works better than breath-based for focus",
    category: "health",
    tags: ["meditation", "mindfulness", "wellness"],
    keywords: ["body scan", "focus", "mental health"],
    createdAt: "2026-02-08T21:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 2,
    emotion: "calm",
    valence: 0.5,
    emotionConfidence: 0.92,
    actionItems: [
      { text: "Stick with body scan meditation for the next week", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "12",
    title: "Grocery delivery optimization",
    body: "Switched from daily small orders to weekly bulk orders. Saves about $40/month in delivery fees alone. Also reduces packaging waste. Made a template shopping list to speed up the process.",
    summary: "Weekly bulk grocery orders save $40/month in delivery fees",
    category: "daily",
    tags: ["groceries", "savings", "efficiency"],
    keywords: ["delivery", "budgeting", "meal planning"],
    createdAt: "2026-02-08T11:20:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 2,
    emotion: "calm",
    emotionSecondary: "grateful",
    valence: 0.3,
    emotionConfidence: 0.7,
    actionItems: [],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "13",
    title: "Team standup improvements",
    body: "Our standups are running too long — averaging 25 minutes. Proposed a new format: each person gets 90 seconds max, blockers get a separate thread. Team agreed to try for two weeks.",
    summary: "Standup meeting reform: 90-second cap per person",
    category: "work",
    tags: ["meetings", "productivity", "team"],
    keywords: ["standup", "agile", "time management"],
    createdAt: "2026-02-13T09:30:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "determined",
    valence: 0.3,
    emotionConfidence: 0.8,
    actionItems: [{ text: "Review standup format after two-week trial", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "14",
    title: "Dream about flying over cities",
    body: "Had the most vivid dream last night — I was flying over a neon-lit city that felt like Tokyo mixed with a fantasy world. Buildings had floating gardens. Woke up feeling inspired. This could be a great concept for a game or art project.",
    summary: "Vivid flying dream over neon city — creative inspiration",
    category: "dreams",
    tags: ["lucid-dream", "creativity", "art"],
    keywords: ["flying", "neon city", "game concept"],
    createdAt: "2026-02-13T06:00:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "excited",
    emotionSecondary: "hopeful",
    valence: 0.9,
    emotionConfidence: 0.85,
    actionItems: [{ text: "Sketch the neon city concept", completed: false }],
    peopleMentioned: [],
    placesMentioned: ["Tokyo"],
  },
  {
    id: "15",
    title: "Investment portfolio rebalance",
    body: "Tech stocks are up 15% YTD but now overweight at 45% of portfolio. Need to rebalance to 35% target. Considering moving excess into international ETFs and bonds. Will execute trades this weekend.",
    summary: "Rebalancing portfolio: reduce tech from 45% to 35%",
    category: "finance",
    tags: ["investing", "portfolio", "rebalancing"],
    keywords: ["stocks", "ETFs", "diversification"],
    createdAt: "2026-02-12T19:30:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "calm",
    emotionSecondary: "determined",
    valence: 0.2,
    emotionConfidence: 0.8,
    actionItems: [{ text: "Execute portfolio rebalance trades", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "16",
    title: "Idea: AI study buddy app",
    body: "What if there was an AI that reads your notes and quizzes you using spaced repetition? It would understand your weak areas and focus there. Could integrate with Notion or Obsidian. The key differentiator would be conversational quizzing — not just flashcards.",
    summary: "AI study app with conversational quizzing and spaced repetition",
    category: "ideas",
    tags: ["edtech", "AI", "spaced-repetition"],
    keywords: ["study app", "learning", "quizzing"],
    createdAt: "2026-02-11T14:00:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: false,
    importance: 5,
    emotion: "excited",
    emotionSecondary: "curious",
    valence: 0.8,
    emotionConfidence: 0.92,
    actionItems: [
      { text: "Research spaced repetition algorithms", completed: false },
      { text: "Design conversational quiz flow", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "17",
    title: "Deep talk with Mom",
    body: "Called Mom today for an hour. She shared stories about grandpa I'd never heard — his journey as an immigrant, the struggles, the resilience. Reminded me why I'm building Dream Hub. These stories deserve to be preserved.",
    summary: "Phone call with Mom — grandpa's immigrant story inspires mission",
    category: "relationships",
    tags: ["family", "stories", "heritage"],
    keywords: ["parents", "immigration", "legacy"],
    createdAt: "2026-02-10T20:00:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: false,
    importance: 5,
    emotion: "grateful",
    emotionSecondary: "melancholic",
    valence: 0.7,
    emotionConfidence: 0.95,
    actionItems: [{ text: "Record grandpa's stories before they're lost", completed: false }],
    peopleMentioned: ["Mom", "Grandpa"],
    placesMentioned: [],
  },
  {
    id: "18",
    title: "TypeScript utility types deep dive",
    body: "Spent time mastering Pick, Omit, Partial, Required, Record, and mapped types. The 'infer' keyword is incredibly powerful for extracting types from complex generics. Need to use these more in production code instead of 'any'.",
    summary: "Mastering TypeScript utility types and 'infer' keyword",
    category: "learning",
    tags: ["TypeScript", "types", "programming"],
    keywords: ["utility types", "generics", "type safety"],
    createdAt: "2026-02-10T22:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "curious",
    emotionSecondary: "determined",
    valence: 0.4,
    emotionConfidence: 0.85,
    actionItems: [{ text: "Refactor project types to use utility types", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "19",
    title: "Anxiety about launch",
    body: "Can't shake this feeling of anxiety about the upcoming launch. What if nobody uses it? What if it breaks? Deep down I know this is normal pre-launch jitters. Need to channel this energy into preparation rather than worry.",
    summary: "Pre-launch anxiety — channeling worry into preparation",
    category: "emotions",
    tags: ["anxiety", "launch", "mindset"],
    keywords: ["fear", "startup", "mental health"],
    createdAt: "2026-02-13T23:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "anxious",
    emotionSecondary: "determined",
    valence: -0.3,
    emotionConfidence: 0.9,
    actionItems: [{ text: "Write a pre-launch checklist to reduce anxiety", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "20",
    title: "Weekend hiking plan",
    body: "Planning a hike to Mt. Bukhan this Saturday. Trail is 8km round trip, moderate difficulty. Need to pack water, snacks, and the new trekking poles. Weather forecast looks clear. Inviting Jake and Lisa.",
    summary: "Saturday hike to Mt. Bukhan — 8km, packing essentials",
    category: "daily",
    tags: ["hiking", "weekend", "outdoors"],
    keywords: ["nature", "exercise", "planning"],
    createdAt: "2026-02-13T18:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 2,
    emotion: "excited",
    valence: 0.6,
    emotionConfidence: 0.75,
    actionItems: [
      { text: "Pack hiking essentials", completed: false },
      { text: "Confirm with Jake and Lisa", completed: false },
    ],
    peopleMentioned: ["Jake", "Lisa"],
    placesMentioned: ["Mt. Bukhan"],
  },
  {
    id: "21",
    title: "Sleep optimization experiment",
    body: "Starting a 2-week experiment: no screens 1hr before bed, room temp at 19°C, blackout curtains. Tracking sleep quality with my watch. Baseline average is 6.5hrs of quality sleep. Target: 7.5hrs.",
    summary: "2-week sleep optimization: no screens, cool room, blackout curtains",
    category: "health",
    tags: ["sleep", "experiment", "wellness"],
    keywords: ["sleep quality", "habits", "biohacking"],
    createdAt: "2026-02-09T22:30:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 3,
    emotion: "determined",
    valence: 0.3,
    emotionConfidence: 0.8,
    actionItems: [
      { text: "Set up blackout curtains", completed: true },
      { text: "Track sleep data for 2 weeks", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "22",
    title: "Platform as a dream journal",
    body: "Dream Hub could also serve as a dream journal. Users log their dreams, AI finds recurring themes and symbols. Over time, patterns emerge — what you dream about most, emotional arcs, lucid dream triggers. This connects Dream Brain with the Dreams category perfectly.",
    summary: "Dream Hub as AI-powered dream journal with pattern detection",
    category: "dreams",
    tags: ["dream-journal", "AI", "patterns"],
    keywords: ["dream analysis", "recurring themes", "self-discovery"],
    createdAt: "2026-02-11T06:30:00Z",
    isFavorite: true,
    isArchived: false,
    isPinned: true,
    importance: 5,
    emotion: "hopeful",
    emotionSecondary: "excited",
    valence: 0.85,
    emotionConfidence: 0.9,
    actionItems: [{ text: "Design dream journal feature spec", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "23",
    title: "API rate limiting strategy",
    body: "Need to implement proper rate limiting before launch. Considering token bucket algorithm for the API. Should set different tiers: free users get 100 req/min, pro users get 1000. Also need to add retry-after headers.",
    summary: "Token bucket rate limiting: 100 req/min free, 1000 pro",
    category: "work",
    tags: ["API", "rate-limiting", "backend"],
    keywords: ["token bucket", "throttling", "infrastructure"],
    createdAt: "2026-02-14T10:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 4,
    emotion: "determined",
    valence: 0.2,
    emotionConfidence: 0.85,
    actionItems: [
      { text: "Implement token bucket rate limiter", completed: false },
      { text: "Add retry-after response headers", completed: false },
    ],
    peopleMentioned: [],
    placesMentioned: [],
  },
  {
    id: "24",
    title: "Feeling stuck creatively",
    body: "Haven't had a good creative idea in a week. Everything feels derivative. Maybe I need to step away from the screen and get inspired by the real world. Going to visit a museum this weekend and sketch random things.",
    summary: "Creative block — planning museum visit for inspiration",
    category: "emotions",
    tags: ["creativity", "block", "inspiration"],
    keywords: ["creative block", "art", "museum"],
    createdAt: "2026-02-14T16:00:00Z",
    isFavorite: false,
    isArchived: false,
    isPinned: false,
    importance: 2,
    emotion: "melancholic",
    emotionSecondary: "hopeful",
    valence: -0.1,
    emotionConfidence: 0.82,
    actionItems: [{ text: "Visit museum this weekend", completed: false }],
    peopleMentioned: [],
    placesMentioned: [],
  },
];

export const mockConnections: Connection[] = [
  // Ideas cluster
  { sourceId: "1", targetId: "10", score: 0.91, reason: "Both discuss marketing and content strategy" },
  { sourceId: "1", targetId: "9", score: 0.78, reason: "AI-powered automation tools" },
  { sourceId: "1", targetId: "6", score: 0.76, reason: "Business ideas involving AI" },
  { sourceId: "1", targetId: "16", score: 0.85, reason: "AI-powered product ideas" },
  { sourceId: "10", targetId: "16", score: 0.72, reason: "Digital product and content ideas" },
  { sourceId: "16", targetId: "9", score: 0.80, reason: "AI and learning technology" },
  // Work cluster
  { sourceId: "2", targetId: "13", score: 0.82, reason: "Team management and productivity" },
  { sourceId: "2", targetId: "23", score: 0.75, reason: "Pre-launch work and deadlines" },
  { sourceId: "13", targetId: "23", score: 0.70, reason: "Engineering workflow optimization" },
  { sourceId: "2", targetId: "8", score: 0.72, reason: "Professional networking and career topics" },
  // Learning cluster
  { sourceId: "4", targetId: "9", score: 0.88, reason: "Technical learning about AI/web frameworks" },
  { sourceId: "4", targetId: "18", score: 0.85, reason: "Programming language deep dives" },
  { sourceId: "9", targetId: "18", score: 0.78, reason: "Technical learning and coding" },
  { sourceId: "18", targetId: "23", score: 0.65, reason: "TypeScript in backend API development" },
  // Health cluster
  { sourceId: "5", targetId: "11", score: 0.80, reason: "Health and wellness routines" },
  { sourceId: "5", targetId: "21", score: 0.82, reason: "Physical health optimization" },
  { sourceId: "11", targetId: "21", score: 0.78, reason: "Wellness and sleep habits" },
  { sourceId: "20", targetId: "5", score: 0.70, reason: "Physical activity and outdoor exercise" },
  // Dreams cluster
  { sourceId: "6", targetId: "14", score: 0.85, reason: "Visionary dream concepts" },
  { sourceId: "6", targetId: "22", score: 0.90, reason: "Dream Hub vision and dream journaling" },
  { sourceId: "14", targetId: "22", score: 0.88, reason: "Dreams and pattern discovery" },
  { sourceId: "22", targetId: "1", score: 0.72, reason: "AI-powered platform features" },
  // Finance cluster
  { sourceId: "7", targetId: "12", score: 0.82, reason: "Personal finance and cost optimization" },
  { sourceId: "7", targetId: "15", score: 0.88, reason: "Financial planning and investment" },
  { sourceId: "15", targetId: "12", score: 0.65, reason: "Money management" },
  // Relationships cluster
  { sourceId: "8", targetId: "17", score: 0.80, reason: "Family and personal connections" },
  { sourceId: "17", targetId: "22", score: 0.75, reason: "Stories worth preserving — Dream Hub mission" },
  { sourceId: "8", targetId: "20", score: 0.68, reason: "Social plans and meetups" },
  // Emotions cluster
  { sourceId: "3", targetId: "11", score: 0.75, reason: "Emotional wellbeing and mindfulness" },
  { sourceId: "3", targetId: "19", score: 0.72, reason: "Emotional self-awareness" },
  { sourceId: "19", targetId: "24", score: 0.85, reason: "Emotional challenges and creative blocks" },
  { sourceId: "24", targetId: "14", score: 0.70, reason: "Creativity and inspiration seeking" },
  // Cross-category connections (the most interesting ones)
  { sourceId: "6", targetId: "1", score: 0.76, reason: "Entrepreneurial AI-powered concepts" },
  { sourceId: "16", targetId: "4", score: 0.82, reason: "Learning tech meets AI product ideas" },
  { sourceId: "17", targetId: "3", score: 0.70, reason: "Gratitude and family warmth" },
  { sourceId: "19", targetId: "2", score: 0.68, reason: "Launch anxiety tied to work deadlines" },
  { sourceId: "21", targetId: "3", score: 0.65, reason: "Wellness and positive mindset" },
  { sourceId: "20", targetId: "8", score: 0.60, reason: "Social activities with friends" },
];

export function getThoughtById(id: string): Thought | undefined {
  return mockThoughts.find((t) => t.id === id);
}

export function getRelatedThoughts(thoughtId: string): Array<{ thought: Thought; score: number; reason: string }> {
  return mockConnections
    .filter((c) => c.sourceId === thoughtId)
    .map((c) => {
      const thought = getThoughtById(c.targetId);
      if (!thought) return null;
      return { thought, score: c.score, reason: c.reason };
    })
    .filter((r): r is NonNullable<typeof r> => r !== null)
    .sort((a, b) => b.score - a.score);
}
