export { prisma } from "./client";
export type {
  User,
  Account,
  Session,
  Thought,
  ThoughtConnection,
  ThoughtCategory,
  InputMethod,
  DreamStory,
  Milestone,
  Product,
  DreamProfile,
  Match,
  MatchStatus,
  Message,
  Order,
  Follow,
  DreamUpdate,
  DreamComment,
  OrderStatus,
  InsightReport,
} from "@prisma/client";
